### ISSUE TITLE
Ex04: Problems

### ISSUE THREAD

**Issue by fayolle** [Hiroki-Nemoto/cpp_exercises#10]
@Hiroki-Nemoto The code is not const-correct. The member functions ```get_``` should all be ```const``` member functions. 

The ```inc_``` functions could be improved by considering that the number of days per month are limited, and similarly for the number of months per year.

**Comment by Hiroki-Nemoto** [comment]
Thank you for looking at my code.
I fixed the part you pointed out, please check it.

**Comment by fayolle** [comment]
@Hiroki-Nemoto None of the ```get_``` member functions are const member functions. 

https://github.com/Hiroki-Nemoto/cpp_exercises/blob/00abae3ea11e1eea371ae57d7b9d01ffdada8371/ex04/Date.cpp#L27
and
https://github.com/Hiroki-Nemoto/cpp_exercises/blob/00abae3ea11e1eea371ae57d7b9d01ffdada8371/ex04/Date.cpp#L29
are not doing what you think they do. 
When you write ```if (a,b,c)``` only ```c``` is checked as a conditional statement.

**Comment by Hiroki-Nemoto** [comment]
> @Hiroki-Nemoto None of the `get_` member functions are const member functions.
> 
> https://github.com/Hiroki-Nemoto/cpp_exercises/blob/00abae3ea11e1eea371ae57d7b9d01ffdada8371/ex04/Date.cpp#L27
> 
> 
> and
> https://github.com/Hiroki-Nemoto/cpp_exercises/blob/00abae3ea11e1eea371ae57d7b9d01ffdada8371/ex04/Date.cpp#L29
> 
> 
> are not doing what you think they do.
> When you write `if (a,b,c)` only `c` is checked as a conditional statement.

I fixed my code, so please check.

**Comment by fayolle** [comment]
Thank you. Looks good.
