### ISSUE TITLE
Ex07 - q1: Wrong directory 

### ISSUE THREAD

**Issue by fayolle** [Hiroki-Nemoto/cpp_exercises#12]
@Hiroki-Nemoto The code for ex07 - q1 is in the wrong directory (it is in the directory ex06).

**Comment by Hiroki-Nemoto** [comment]
> @Hiroki-Nemoto The code for ex07 - q1 is in the wrong directory (it is in the directory ex06).

I made directory ex07, so please check.

**Comment by fayolle** [comment]
@Hiroki-Nemoto I had already looked at the code (stringToInt) that was in ex06 and it looks fine. I am closing this issue.
