### ISSUE TITLE
Ex10 - q2: Incorrect 

### ISSUE THREAD

**Issue by fayolle** [Hiroki-Nemoto/cpp_exercises#20]
@Hiroki-Nemoto The code for ex10 - q2 does not seem to be correct. It doesn't pass the provided tests.

**Comment by Hiroki-Nemoto** [comment]
> @Hiroki-Nemoto The code for ex10 - q2 does not seem to be correct. It doesn't pass the provided tests.

I fixed my code.
Could you please check it?

**Comment by fayolle** [comment]
@Hiroki-Nemoto ok it looks fine.
