### ISSUE TITLE
Ex05 - q1: Order in the initialization list 

### ISSUE THREAD

**Issue by fayolle** [Hiroki-Nemoto/cpp_exercises#9]
@Hiroki-Nemoto In 
https://github.com/Hiroki-Nemoto/cpp_exercises/blob/0c0dbd56414bdb58b27a28fcef3c53967fd31f37/ex05/ArrayStack.h#L31 
use the same order as the one used for the member variables. 
Thus, ```_items``` and ```_allocated_size``` should be switched. 

It is possible to write ```_items = new double[allocated_size];``` directly (without introducing a temp variable).

**Comment by Hiroki-Nemoto** [comment]
> @Hiroki-Nemoto In
> 
> https://github.com/Hiroki-Nemoto/cpp_exercises/blob/0c0dbd56414bdb58b27a28fcef3c53967fd31f37/ex05/ArrayStack.h#L31
> 
> 
> use the same order as the one used for the member variables.
> Thus, `_items` and `_allocated_size` should be switched.
> It is possible to write `_items = new double[allocated_size];` directly (without introducing a temp variable).

Thank you for looking at my code.
I fixed the order of _items and _allocated_size.
Please check it.

**Comment by fayolle** [comment]
OK. Thank you.
